<a href="https://colab.research.google.com/github/a2w3r4/Basic-Neural-Network-using-Pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
2+2

4

In [3]:
import torch

# Tensors

> A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

> Similar to Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU).

>default data type os float32

> More suitable for deep learning than a numpy array.

In [4]:
import torch
import numpy as np

# LISTS

In [5]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]     #Python
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NUMPY ARRAYS

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.7968561 , 0.69866149, 0.81407131, 0.81076798],
       [0.5100641 , 0.99882412, 0.65974531, 0.56167322],
       [0.09483768, 0.65898767, 0.30873116, 0.6319646 ]])

In [7]:
np1.dtype

dtype('float64')

# **TENSORS**

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d


tensor([[-0.7938,  1.3786,  0.4905,  1.2542],
        [-0.9069, -0.3473, -0.3689, -1.6024],
        [-1.2543,  0.4813,  1.0770,  0.7597]])

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [10]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7969, 0.6987, 0.8141, 0.8108],
        [0.5101, 0.9988, 0.6597, 0.5617],
        [0.0948, 0.6590, 0.3087, 0.6320]], dtype=torch.float64)

# Tensor Operations


In [12]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [20]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [21]:
# Slices

In [22]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#Grab a specific item
my_torch7[7]

tensor(7)

In [24]:
my_torch8 = my_torch7.reshape(5, 2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [25]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [26]:
# Return Column

In [27]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

# Tensor Math Operation

In [28]:
import torch

In [29]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [30]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

Addition

In [31]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

Subtraction

In [32]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [33]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

Multiplication

In [34]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [40]:
torch.mul( tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

Division

In [35]:
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

Modulus

In [36]:
tensor_a % tensor_b

tensor([1, 2, 3, 4])

In [42]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [43]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [44]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

Reassignment

In [45]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [46]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [49]:
tensor_a = tensor_a + tensor_b
tensor_a

tensor([16, 20, 24, 28])

In [47]:
tensor_a

tensor([ 6,  8, 10, 12])